#!/usr/bin/env bash
set -euo pipefail

# Run on the Orin to remove the configuration installed by
# orin-one-time-setup.sh. A later run of the setup script creates a fresh,
# reversible configuration again.

CONFIG_FILE="${ORIN_AUTO_WIFI_CONFIG:-/etc/orin-auto-wifi.conf}"
LEGACY_AVAHI_BACKUP_FILE="/etc/avahi/avahi-daemon.conf.bak"
TARGET_FILE="${ORIN_WIFI_TARGET_FILE:-/etc/orin-wifi-target}"

IOTSWARM_CON="${IOTSWARM_CON:-iotswarm_5G}"
IOTLAB_CON="${IOTLAB_CON:-IoTLab_5G}"
REMOVE_WIFI_PROFILES="${REMOVE_WIFI_PROFILES:-yes}"
REENABLE_WIFI_AUTOCONNECT="${REENABLE_WIFI_AUTOCONNECT:-yes}"

refresh_state_paths() {
  STATE_DIR="${ORIN_WIFI_STATE_DIR:-/etc/orin-nomachine-wifi}"
  AUTOCONNECT_STATE_FILE="$STATE_DIR/wifi-autoconnect.before"
  HOSTNAME_STATE_FILE="$STATE_DIR/hostname.before"
  AVAHI_BACKUP_FILE="$STATE_DIR/avahi-daemon.conf.before"
  AVAHI_SERVICE_STATE_FILE="$STATE_DIR/avahi-daemon.enabled.before"
  NXSERVER_SERVICE_STATE_FILE="$STATE_DIR/nxserver.enabled.before"
}

refresh_state_paths

usage() {
  cat <<'EOF'
Usage:
  sudo ./orin-cleanup.sh

This removes the boot WiFi service and helper scripts installed by
orin-one-time-setup.sh, restores saved hostname and Avahi settings, and
reenables automatic connection for the remaining WiFi profiles.

Optional environment variables:
  REMOVE_WIFI_PROFILES=no          Keep the two managed WiFi profiles.
  REENABLE_WIFI_AUTOCONNECT=no     Restore only the saved autoconnect values.
EOF
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

load_setup_config() {
  [ -f "$CONFIG_FILE" ] || return 0
  # This file is generated by orin-one-time-setup.sh with shell-escaped values.
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
  refresh_state_paths
}

connection_exists_uuid() {
  nmcli -t -f UUID connection show | awk -F: -v uuid="$1" '$1 == uuid {found=1} END {exit found ? 0 : 1}'
}

connection_uuids_by_name() {
  nmcli -t -f NAME,UUID connection show | awk -F: -v name="$1" '$1 == name {print $2}'
}

restore_saved_autoconnect() {
  local uuid autoconnect

  [ -f "$AUTOCONNECT_STATE_FILE" ] || return 0
  while IFS=$'\t' read -r uuid autoconnect; do
    [ -n "$uuid" ] || continue
    connection_exists_uuid "$uuid" || continue
    nmcli connection modify "$uuid" connection.autoconnect "$autoconnect" >/dev/null 2>&1 || true
  done < "$AUTOCONNECT_STATE_FILE"
}

delete_wifi_profile() {
  local name="$1"
  local uuid

  while IFS= read -r uuid; do
    [ -n "$uuid" ] || continue
    nmcli connection delete "$uuid" >/dev/null 2>&1 || true
  done < <(connection_uuids_by_name "$name")
}

reenable_remaining_wifi_autoconnect() {
  local uuid type

  [ "$REENABLE_WIFI_AUTOCONNECT" = "yes" ] || return 0
  while IFS=: read -r uuid type; do
    [ "$type" = "802-11-wireless" ] || [ "$type" = "wifi" ] || continue
    [ -n "$uuid" ] || continue
    nmcli connection modify "$uuid" connection.autoconnect yes >/dev/null 2>&1 || true
  done < <(nmcli -t -f UUID,TYPE connection show)
  nmcli networking on >/dev/null 2>&1 || true
  nmcli radio wifi on >/dev/null 2>&1 || true
}

restore_avahi_config() {
  local conf="/etc/avahi/avahi-daemon.conf"
  local backup_file="$AVAHI_BACKUP_FILE"

  if [ ! -f "$backup_file" ] && [ -f "$LEGACY_AVAHI_BACKUP_FILE" ]; then
    backup_file="$LEGACY_AVAHI_BACKUP_FILE"
  fi
  [ -f "$backup_file" ] || return 0
  cp -f "$backup_file" "$conf"
  systemctl restart avahi-daemon.service >/dev/null 2>&1 || true
}

restore_hostname() {
  local hostname_before

  [ -f "$HOSTNAME_STATE_FILE" ] || return 0
  hostname_before="$(head -n 1 "$HOSTNAME_STATE_FILE" | tr -d '\r')"
  [ -n "$hostname_before" ] || return 0
  hostnamectl set-hostname "$hostname_before" 2>/dev/null || true
}

restore_service_enabled_state() {
  local service="$1"
  local state_file="$2"
  local state

  [ -f "$state_file" ] || return 0
  state="$(head -n 1 "$state_file" | tr -d '\r')"
  case "$state" in
    yes)
      systemctl enable --now "$service" >/dev/null 2>&1 || true
      ;;
    no)
      systemctl disable --now "$service" >/dev/null 2>&1 || true
      ;;
  esac
}

remove_installed_files() {
  systemctl disable --now orin-auto-wifi.service >/dev/null 2>&1 || true
  rm -f /etc/systemd/system/orin-auto-wifi.service
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl reset-failed orin-auto-wifi.service >/dev/null 2>&1 || true

  rm -f /usr/local/sbin/orin-auto-wifi
  rm -f /usr/local/sbin/orin-switch-wifi
  rm -f /usr/local/sbin/orin-wifi-cleanup
  rm -f "$CONFIG_FILE" "$TARGET_FILE" /var/log/orin-switch-wifi.log
}

remove_rollback_state() {
  rm -f "$AUTOCONNECT_STATE_FILE" "$HOSTNAME_STATE_FILE" "$AVAHI_BACKUP_FILE"
  rm -f "$AVAHI_SERVICE_STATE_FILE" "$NXSERVER_SERVICE_STATE_FILE"
  rmdir "$STATE_DIR" 2>/dev/null || true
}

setup_is_present() {
  [ -f "$CONFIG_FILE" ] || \
    [ -f /etc/systemd/system/orin-auto-wifi.service ] || \
    [ -f /usr/local/sbin/orin-auto-wifi ] || \
    [ -f /usr/local/sbin/orin-switch-wifi ] || \
    [ -f /usr/local/sbin/orin-wifi-cleanup ] || \
    [ -f "$AUTOCONNECT_STATE_FILE" ] || \
    [ -f "$HOSTNAME_STATE_FILE" ] || \
    [ -f "$AVAHI_BACKUP_FILE" ] || \
    [ -f "$AVAHI_SERVICE_STATE_FILE" ] || \
    [ -f "$NXSERVER_SERVICE_STATE_FILE" ]
}

main() {
  case "${1:-}" in
    -h|--help|help)
      usage
      exit 0
      ;;
    '')
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac

  [ "${EUID:-$(id -u)}" -eq 0 ] || die "run this on the Orin with sudo"
  command -v nmcli >/dev/null 2>&1 || die "nmcli is required"
  setup_is_present || die "no Orin NoMachine WiFi setup was found"

  load_setup_config
  remove_installed_files
  restore_saved_autoconnect

  if [ "$REMOVE_WIFI_PROFILES" = "yes" ]; then
    delete_wifi_profile "$IOTSWARM_CON"
    delete_wifi_profile "$IOTLAB_CON"
  fi

  reenable_remaining_wifi_autoconnect
  restore_avahi_config
  restore_hostname
  restore_service_enabled_state avahi-daemon.service "$AVAHI_SERVICE_STATE_FILE"
  restore_service_enabled_state nxserver.service "$NXSERVER_SERVICE_STATE_FILE"
  remove_rollback_state

  printf 'Removed the Orin NoMachine WiFi setup.\n'
  if [ "$REMOVE_WIFI_PROFILES" = "yes" ]; then
    printf 'Deleted WiFi profiles: %s, %s\n' "$IOTSWARM_CON" "$IOTLAB_CON"
  else
    printf 'Kept WiFi profiles: %s, %s\n' "$IOTSWARM_CON" "$IOTLAB_CON"
  fi
  if [ "$REENABLE_WIFI_AUTOCONNECT" = "yes" ]; then
    printf 'Enabled automatic connection for all remaining WiFi profiles.\n'
  fi
  printf 'To enable this workflow again, run orin-one-time-setup.sh again.\n'
}

main "$@"
